#!/usr/bin/env python3
"""AETHON Spectrogram CNN Training and Evaluation CLI.

Trains and evaluates a lightweight 5-class 2D CNN classifier on synthetic
spectrogram datasets generated by prepare_cnn_dataset.py.

Workflow:
1. Loads compressed .npz dataset and verifies companion manifest statistics.
2. Applies strictly training-derived Z-score normalization across all splits.
3. Trains SpectrogramCNN on the training split using cross-entropy loss and Adam.
4. Performs early stopping based on validation split loss.
5. Evaluates the final selected checkpoint on the held-out test split.
6. Saves model checkpoint (.pt) and comprehensive JSON evaluation report.

Usage Examples:
  # Train with default dataset and output paths:
  python backend/scripts/train_cnn_classifier.py

  # Train with explicit parameters:
  python backend/scripts/train_cnn_classifier.py --epochs 25 --batch-size 32 --seed 42 --overwrite
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import platform
import random
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Ensure backend root is on sys.path
_SCRIPT_DIR = Path(__file__).resolve().parent
_BACKEND_ROOT = _SCRIPT_DIR.parent
_REPO_ROOT = _BACKEND_ROOT.parent if _BACKEND_ROOT.name == "backend" else _BACKEND_ROOT

if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

try:
    import numpy as np
    import sklearn
    import torch
    import torch.nn as nn
    from sklearn.metrics import classification_report, confusion_matrix
    from torch.utils.data import DataLoader, TensorDataset

    from app.detection.cnn_classifier import (
        CLASS_NAMES,
        NUM_CLASSES,
        SpectrogramCNN,
        count_parameters,
        normalize_spectrogram,
    )
except ImportError as err:
    print(
        f"ERROR: Missing required backend dependency: {err}\n"
        f"Please run this script using the AETHON backend virtual environment, for example:\n"
        f"  backend\\.venv\\Scripts\\python.exe backend/scripts/train_cnn_classifier.py\n"
        f"or:\n"
        f"  source backend/.venv/bin/activate && python backend/scripts/train_cnn_classifier.py",
        file=sys.stderr,
    )
    sys.exit(1)


DEFAULT_DATASET_PATH = _BACKEND_ROOT / "data" / "cnn_dataset" / "aethon_spectrogram_cnn.npz"
DEFAULT_OUTPUT_DIR = _BACKEND_ROOT / "data" / "cnn_models"
DEFAULT_SEED = 42
DEFAULT_EPOCHS = 30
DEFAULT_BATCH_SIZE = 32
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_PATIENCE = 7


def compute_file_sha256(path: Path) -> str:
    """Compute SHA-256 hex digest of a file in streaming chunks."""
    hasher = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(65536):
            hasher.update(chunk)
    return hasher.hexdigest()


def set_deterministic_seeds(seed: int) -> None:
    """Set global random seeds for Python, NumPy, and PyTorch for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def train_and_evaluate_cnn(
    dataset_path: Path,
    output_dir: Path,
    seed: int = DEFAULT_SEED,
    epochs: int = DEFAULT_EPOCHS,
    batch_size: int = DEFAULT_BATCH_SIZE,
    learning_rate: float = DEFAULT_LEARNING_RATE,
    patience: int = DEFAULT_PATIENCE,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Execute complete reproducible training and evaluation pipeline."""
    dataset_path = dataset_path.resolve()
    output_dir = output_dir.resolve()
    checkpoint_path = output_dir / "spectrogram_cnn.pt"
    report_path = output_dir / "training_report.json"

    print("=====================================================================")
    print("        AETHON — Experimental Spectrogram CNN Training Gate          ")
    print("=====================================================================")
    print(f"Timestamp:       {datetime.now(UTC).isoformat()}")
    print(f"Dataset Path:    {dataset_path}")
    print(f"Output Dir:      {output_dir}")
    print(f"Master Seed:     {seed}")
    print("Device:          CPU (deterministic)")
    print(
        f"Hyperparameters: epochs={epochs}, batch_size={batch_size}, lr={learning_rate}, patience={patience}"
    )
    print("---------------------------------------------------------------------")

    # Safety Guard: Check if output files already exist
    if (checkpoint_path.exists() or report_path.exists()) and not overwrite:
        existing = [p.name for p in [checkpoint_path, report_path] if p.exists()]
        raise RuntimeError(
            f"SAFETY ABORT: Target output file(s) already exist at {output_dir}:\n"
            f"  {', '.join(existing)}\n"
            f"The trainer refuses to silently overwrite existing checkpoints or reports.\n"
            f"To allow replacement, specify the --overwrite flag,\n"
            f"or choose a different output directory via --output-dir."
        )

    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Dataset archive not found at: {dataset_path}\n"
            f"Please generate the dataset first using:\n"
            f"  python backend/scripts/prepare_cnn_dataset.py"
        )

    # 1. Load Dataset Archive
    print("\n[Step 1/5] Loading and verifying dataset archive...")
    dataset_sha256 = compute_file_sha256(dataset_path)
    data = np.load(dataset_path)

    train_x = data["train_images"]  # shape (N_train, 32, 32), float32
    train_y = data["train_labels"]  # shape (N_train,), int64
    val_x = data["val_images"]  # shape (N_val, 32, 32), float32
    val_y = data["val_labels"]  # shape (N_val,), int64
    test_x = data["test_images"]  # shape (N_test, 32, 32), float32
    test_y = data["test_labels"]  # shape (N_test,), int64
    class_names = [str(c) for c in data["class_names"]]

    print(f"  Archive SHA-256: {dataset_sha256}")
    print(f"  Train samples:   {train_x.shape[0]} ({train_x.shape[1]}x{train_x.shape[2]})")
    print(f"  Val samples:     {val_x.shape[0]}")
    print(f"  Test samples:    {test_x.shape[0]}")
    print(f"  Classes:         {class_names}")

    if class_names != CLASS_NAMES:
        raise ValueError(f"Class names mismatch: Dataset has {class_names}, expected {CLASS_NAMES}")

    # 2. Verify Normalization Statistics
    print("\n[Step 2/5] Calculating and validating training normalization statistics...")
    calc_mean = float(np.mean(train_x))
    calc_std = float(np.std(train_x))

    if not np.isfinite(calc_std) or calc_std < 1e-8:
        raise ValueError(f"Invalid non-finite or near-zero training std dev: {calc_std}")

    print(f"  Calculated Train Mean: {calc_mean:.6f}")
    print(f"  Calculated Train Std:  {calc_std:.6f}")

    # Check companion manifest if available
    manifest_name = dataset_path.stem + "_manifest.json"
    manifest_path = dataset_path.parent / manifest_name
    manifest_identity = manifest_path.name if manifest_path.exists() else None

    if manifest_path.exists():
        with open(manifest_path, encoding="utf-8") as f_man:
            man_data = json.load(f_man)
        man_mean = man_data.get("normalization_parameters", {}).get("train_mean")
        man_std = man_data.get("normalization_parameters", {}).get("train_std")

        if man_mean is not None and man_std is not None:
            if not np.isclose(calc_mean, man_mean, atol=1e-4) or not np.isclose(
                calc_std, man_std, atol=1e-4
            ):
                raise RuntimeError(
                    f"DISCREPANCY DETECTED between dataset array and manifest normalization statistics!\n"
                    f"  Array stats:    mean={calc_mean:.6f}, std={calc_std:.6f}\n"
                    f"  Manifest stats: mean={man_mean:.6f}, std={man_std:.6f}\n"
                    f"Aborting training to maintain strict scientific reproducibility."
                )
            print("  Manifest Statistics: Verified agreement within tolerance.")

    # Apply strictly training-derived normalization to all splits
    train_x_norm = normalize_spectrogram(train_x, calc_mean, calc_std)
    val_x_norm = normalize_spectrogram(val_x, calc_mean, calc_std)
    test_x_norm = normalize_spectrogram(test_x, calc_mean, calc_std)

    # Prepare PyTorch Tensors and DataLoaders
    train_tensor_x = torch.from_numpy(train_x_norm).unsqueeze(1).float()  # (N, 1, 32, 32)
    train_tensor_y = torch.from_numpy(train_y).long()
    val_tensor_x = torch.from_numpy(val_x_norm).unsqueeze(1).float()
    val_tensor_y = torch.from_numpy(val_y).long()
    test_tensor_x = torch.from_numpy(test_x_norm).unsqueeze(1).float()
    test_tensor_y = torch.from_numpy(test_y).long()

    set_deterministic_seeds(seed)
    train_loader = DataLoader(
        TensorDataset(train_tensor_x, train_tensor_y),
        batch_size=batch_size,
        shuffle=True,
    )
    val_loader = DataLoader(
        TensorDataset(val_tensor_x, val_tensor_y),
        batch_size=batch_size,
        shuffle=False,
    )
    test_loader = DataLoader(
        TensorDataset(test_tensor_x, test_tensor_y),
        batch_size=batch_size,
        shuffle=False,
    )

    # 3. Model Instantiation
    print("\n[Step 3/5] Instantiating SpectrogramCNN model...")
    device = torch.device("cpu")
    model = SpectrogramCNN(num_classes=NUM_CLASSES).to(device)
    param_count = count_parameters(model)
    print("  Architecture:    SpectrogramCNN (3 Conv stages + AdaptiveAvgPool + MLP Head)")
    print(f"  Trainable Params: {param_count:,}")

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)

    # 4. Training Loop with Early Stopping
    print(f"\n[Step 4/5] Training for up to {epochs} epochs on CPU...")
    best_val_loss = float("inf")
    best_val_acc = 0.0
    best_val_macro_f1 = 0.0
    best_model_weights: dict[str, torch.Tensor] = {}
    patience_counter = 0
    actual_epochs_trained = 0
    early_stopped = False

    for epoch in range(1, epochs + 1):
        actual_epochs_trained = epoch
        model.train()
        running_train_loss = 0.0
        train_correct = 0

        for batch_x, batch_y in train_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            optimizer.zero_grad()
            logits = model(batch_x)
            loss = criterion(logits, batch_y)
            loss.backward()
            optimizer.step()

            running_train_loss += loss.item() * batch_x.size(0)
            preds = torch.argmax(logits, dim=1)
            train_correct += (preds == batch_y).sum().item()

        epoch_train_loss = running_train_loss / len(train_tensor_x)
        epoch_train_acc = train_correct / len(train_tensor_x)

        # Validation Step
        model.eval()
        running_val_loss = 0.0
        val_preds_list: list[int] = []
        val_targets_list: list[int] = []

        with torch.no_grad():
            for val_batch_x, val_batch_y in val_loader:
                val_batch_x, val_batch_y = val_batch_x.to(device), val_batch_y.to(device)
                logits = model(val_batch_x)
                loss = criterion(logits, val_batch_y)
                running_val_loss += loss.item() * val_batch_x.size(0)
                preds = torch.argmax(logits, dim=1)
                val_preds_list.extend(preds.cpu().tolist())
                val_targets_list.extend(val_batch_y.cpu().tolist())

        epoch_val_loss = running_val_loss / len(val_tensor_x)
        val_report = classification_report(
            val_targets_list,
            val_preds_list,
            target_names=CLASS_NAMES,
            output_dict=True,
            zero_division=0,
        )
        epoch_val_acc = float(val_report["accuracy"])
        epoch_val_f1 = float(val_report["macro avg"]["f1-score"])

        # Early Stopping Logic
        if epoch_val_loss < best_val_loss:
            best_val_loss = epoch_val_loss
            best_val_acc = epoch_val_acc
            best_val_macro_f1 = epoch_val_f1
            best_model_weights = copy.deepcopy(model.state_dict())
            patience_counter = 0
            improved_marker = "(* best)"
        else:
            patience_counter += 1
            improved_marker = f"(patience {patience_counter}/{patience})"

        if epoch % 5 == 0 or epoch == 1 or improved_marker.startswith("(*"):
            print(
                f"  Epoch {epoch:2d}/{epochs:2d} | "
                f"Train Loss: {epoch_train_loss:.4f}, Acc: {epoch_train_acc:.3f} | "
                f"Val Loss: {epoch_val_loss:.4f}, Acc: {epoch_val_acc:.3f}, F1: {epoch_val_f1:.3f} {improved_marker}"
            )

        if patience_counter >= patience:
            print(f"  Early stopping triggered after epoch {epoch}.")
            early_stopped = True
            break

    print(
        f"  Selected Checkpoint: Best Val Loss={best_val_loss:.4f}, "
        f"Val Acc={best_val_acc:.3f}, Val Macro-F1={best_val_macro_f1:.3f}"
    )

    # Load best checkpoint weights
    model.load_state_dict(best_model_weights)

    # 5. Held-Out Test Evaluation
    print("\n[Step 5/5] Evaluating on held-out test split...")
    model.eval()
    running_test_loss = 0.0
    test_preds_list: list[int] = []
    test_targets_list: list[int] = []

    with torch.no_grad():
        for test_batch_x, test_batch_y in test_loader:
            test_batch_x, test_batch_y = test_batch_x.to(device), test_batch_y.to(device)
            logits = model(test_batch_x)
            loss = criterion(logits, test_batch_y)
            running_test_loss += loss.item() * test_batch_x.size(0)
            preds = torch.argmax(logits, dim=1)
            test_preds_list.extend(preds.cpu().tolist())
            test_targets_list.extend(test_batch_y.cpu().tolist())

    test_loss = running_test_loss / len(test_tensor_x)
    test_report_dict = classification_report(
        test_targets_list,
        test_preds_list,
        target_names=CLASS_NAMES,
        output_dict=True,
        zero_division=0,
    )
    conf_matrix = confusion_matrix(test_targets_list, test_preds_list).tolist()
    overall_accuracy = float(test_report_dict["accuracy"])
    macro_f1 = float(test_report_dict["macro avg"]["f1-score"])

    print(f"  Test Loss:        {test_loss:.4f}")
    print(f"  Test Accuracy:    {overall_accuracy:.4f} ({overall_accuracy * 100:.1f}%)")
    print(f"  Test Macro-F1:    {macro_f1:.4f}")
    print("\n  Per-Class Test Performance:")
    per_class_summary: dict[str, dict[str, float]] = {}
    for name in CLASS_NAMES:
        cls_data = test_report_dict[name]
        per_class_summary[name] = {
            "precision": round(float(cls_data["precision"]), 4),
            "recall": round(float(cls_data["recall"]), 4),
            "f1_score": round(float(cls_data["f1-score"]), 4),
            "support": int(cls_data["support"]),
        }
        print(
            f"    - {name:<16}: Precision={cls_data['precision']:.3f}, "
            f"Recall={cls_data['recall']:.3f}, F1={cls_data['f1-score']:.3f} (n={cls_data['support']})"
        )

    print("\n  Confusion Matrix (rows=true, cols=pred):")
    for row_name, row_vals in zip(CLASS_NAMES, conf_matrix, strict=True):
        print(f"    {row_name:<16}: {row_vals}")

    # 6. Save Checkpoint and Comprehensive Report
    output_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_payload = {
        "model_architecture": "SpectrogramCNN",
        "state_dict": best_model_weights,
        "num_classes": NUM_CLASSES,
        "class_names": CLASS_NAMES,
        "normalization": {
            "train_mean": calc_mean,
            "train_std": calc_std,
        },
        "input_shape": [1, 32, 32],
        "training_metadata": {
            "seed": seed,
            "epochs_trained": actual_epochs_trained,
            "best_val_loss": best_val_loss,
            "test_accuracy": overall_accuracy,
            "test_macro_f1": macro_f1,
            "created_at_utc": datetime.now(UTC).isoformat(),
        },
    }
    torch.save(checkpoint_payload, checkpoint_path)
    checkpoint_sha256 = compute_file_sha256(checkpoint_path)
    print(
        f"\n  Saved Checkpoint: {checkpoint_path.name} ({checkpoint_path.stat().st_size:,} bytes)"
    )

    report_payload: dict[str, Any] = {
        "report_version": "1.0.0",
        "provenance": "synthetic_experimental_cnn_training",
        "created_at_utc": datetime.now(UTC).isoformat(),
        "dataset": {
            "archive_name": dataset_path.name,
            "archive_sha256": dataset_sha256,
            "manifest_identity": manifest_identity,
            "sample_counts": {
                "train": int(train_x.shape[0]),
                "val": int(val_x.shape[0]),
                "test": int(test_x.shape[0]),
                "total": int(train_x.shape[0] + val_x.shape[0] + test_x.shape[0]),
            },
            "class_names": CLASS_NAMES,
            "sample_shape": [int(train_x.shape[1]), int(train_x.shape[2])],
        },
        "normalization": {
            "train_mean": round(calc_mean, 6),
            "train_std": round(calc_std, 6),
            "computed_from": "train_split_only",
        },
        "model_architecture": {
            "name": "SpectrogramCNN",
            "parameters_count": param_count,
            "input_shape": [1, 32, 32],
            "num_classes": NUM_CLASSES,
            "feature_extractor": "3-stage Conv2D + BatchNorm + MaxPool/AdaptiveAvgPool",
            "classifier_head": "Flatten + Dropout(0.2) + Linear(512->64) + ReLU + Linear(64->5)",
        },
        "hyperparameters": {
            "master_seed": seed,
            "optimizer": "Adam",
            "learning_rate": learning_rate,
            "weight_decay": 1e-4,
            "batch_size": batch_size,
            "epoch_limit": epochs,
            "actual_epochs_trained": actual_epochs_trained,
            "early_stopping_patience": patience,
            "early_stopped": early_stopped,
            "device": "cpu",
        },
        "validation_performance": {
            "best_val_loss": round(best_val_loss, 4),
            "best_val_accuracy": round(best_val_acc, 4),
            "best_val_macro_f1": round(best_val_macro_f1, 4),
        },
        "test_performance": {
            "test_loss": round(test_loss, 4),
            "overall_accuracy": round(overall_accuracy, 4),
            "macro_f1": round(macro_f1, 4),
            "per_class_metrics": per_class_summary,
            "confusion_matrix": conf_matrix,
        },
        "environment": {
            "python_version": sys.version.split()[0],
            "numpy_version": np.__version__,
            "torch_version": torch.__version__,
            "sklearn_version": sklearn.__version__,
            "platform": platform.platform(),
            "cpu_architecture": platform.machine(),
        },
        "disclaimer": (
            "Strictly synthetic experimental numerical evaluation. Evaluated exclusively "
            "on synthetic spectrogram benchmarks generated by AETHON's controlled simulator. "
            "Metrics do not establish astrophysical discovery capability or classification performance "
            "on real uncalibrated telescope data. The CNN is an offline prototype and does not replace "
            "AETHON's production anomaly detection and spatial verification baseline."
        ),
        "artifacts": {
            "checkpoint_file": checkpoint_path.name,
            "checkpoint_sha256": checkpoint_sha256,
            "report_file": report_path.name,
        },
    }

    with open(report_path, "w", encoding="utf-8") as f_rep:
        json.dump(report_payload, f_rep, indent=2)
    print(f"  Saved Report:     {report_path.name}")
    print("=====================================================================")
    print("SUCCESS: Spectrogram CNN trained, evaluated, and saved successfully.")
    print("=====================================================================")

    return {
        "checkpoint_path": str(checkpoint_path),
        "report_path": str(report_path),
        "test_accuracy": overall_accuracy,
        "test_macro_f1": macro_f1,
        "confusion_matrix": conf_matrix,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train and evaluate AETHON's experimental Spectrogram CNN on synthetic datasets.",
        epilog=(
            "Example usage:\n"
            "  python backend/scripts/train_cnn_classifier.py\n"
            "  python backend/scripts/train_cnn_classifier.py --epochs 25 --batch-size 32 --seed 42 --overwrite\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--dataset-path",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help="Path to compressed .npz dataset archive (default: backend/data/cnn_dataset/aethon_spectrogram_cnn.npz)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to save model checkpoint and JSON report (default: backend/data/cnn_models/)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Deterministic master seed (default: 42)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=DEFAULT_EPOCHS,
        help="Maximum training epochs (default: 30)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help="Mini-batch size (default: 32)",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=DEFAULT_LEARNING_RATE,
        help="Initial learning rate (default: 0.001)",
    )
    parser.add_argument(
        "--patience",
        type=int,
        default=DEFAULT_PATIENCE,
        help="Early stopping patience in epochs (default: 7)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow replacing existing model checkpoint and training report",
    )

    args = parser.parse_args()

    try:
        train_and_evaluate_cnn(
            dataset_path=args.dataset_path,
            output_dir=args.output_dir,
            seed=args.seed,
            epochs=args.epochs,
            batch_size=args.batch_size,
            learning_rate=args.learning_rate,
            patience=args.patience,
            overwrite=args.overwrite,
        )
    except RuntimeError as err:
        print(str(err), file=sys.stderr)
        sys.exit(1)
    except Exception as err:
        print(f"Unexpected fatal error: {err}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
