export function ExecutiveSummarySection() {
  return (
    <section id="executive-summary" className="space-y-6 scroll-mt-24">
      {/* Chapter Number & Title */}
      <div className="space-y-1 border-b border-[#E4E1D9] pb-3">
        <div className="font-mono text-xs text-[#376A9B] font-semibold tracking-wider uppercase">
          01 / Executive Summary
        </div>
        <h2 className="text-2xl sm:text-3xl font-serif font-normal text-[#17202A] tracking-tight">
          Scientific Mission & Conceptual Thesis
        </h2>
        <p className="text-xs text-[#7E8B96] font-mono">
          Core thesis, scientific mission, and end-to-end conceptual discovery pipeline.
        </p>
      </div>

      {/* Prose Narrative */}
      <div className="space-y-4 text-base text-[#56616A] leading-relaxed font-sans">
        <p>
          <strong className="text-[#17202A] font-medium">Project AETHON</strong> is an open-set
          anomaly discovery framework designed to surface uncatalogued, non-stationary radio
          frequency phenomena in high-cadence astronomical surveys. Modern radio observatories
          collect gigahertz-bandwidth telemetry across thousands of channels simultaneously. The
          vast majority of this incoming volume represents predictable astronomical background (such
          as diffuse galactic synchrotron emission and neutral hydrogen line radiation), alongside
          dense anthropogenic Radio-Frequency Interference (RFI) generated by satellite
          constellations and terrestrial telecommunication transmitters.
        </p>

        <p>
          Conventional astronomical processing relies heavily on closed-world classification:
          algorithms are explicitly trained to match incoming signals against historical templates
          such as known pulsar profiles, fast radio burst dispersion measures, or specific
          terrestrial modulation schemes. However, when exploring uncharacterized astrophysical
          regimes or searching for narrowband extraterrestrial technosignatures,
          <em className="text-[#17202A] font-serif"> no prior ground-truth labels exist</em>.
          Forcing uncatalogued phenomena into predetermined classification bins risks either
          categorizing genuine novelties as mundane noise or overlooking subtle physical
          morphologies that do not match existing templates.
        </p>

        <p>
          AETHON addresses this challenge by shifting the computational objective from
          <em className="font-serif text-[#17202A]"> identification</em> to
          <em className="font-serif text-[#17202A]"> novelty estimation</em>. Rather than asking{' '}
          <span className="font-mono text-xs bg-[#EAE7E0] px-1 py-0.5 rounded-[2px] text-[#17202A]">
            "Which known category does this match?"
          </span>
          , AETHON models the statistical manifold of nominal cosmic observations and asks{' '}
          <span className="font-mono text-xs bg-[#EAE7E0] px-1 py-0.5 rounded-[2px] text-[#17202A]">
            "Does this observation depart significantly from the learned distribution of expected
            sky and instrumental states?"
          </span>
        </p>

        <p>
          Within this architecture, machine learning acts strictly as a high-throughput
          prioritization instrument. The algorithm constructs compact spectrotemporal latent
          embeddings, computes reconstruction residuals and manifold density metrics, and ranks
          anomalies against spatial and Doppler-drift constraints. Crucially, the system does not
          declare scientific discovery autonomously. Human astrophysicists retain total authority
          over candidate verification, multi-frequency cross-checks, and independent observatory
          replication.
        </p>
      </div>

      {/* Figure 01: End-to-End Conceptual Discovery Pipeline */}
      <figure className="my-8 p-5 bg-[#FAF8F5] border border-[#D6D2C9] rounded-[3px] space-y-4 shadow-2xs">
        <div className="flex flex-wrap items-center justify-between gap-2 text-xs font-mono border-b border-[#E4E1D9] pb-2.5">
          <span className="font-semibold text-[#17202A]">
            FIGURE 01 — End-to-End Conceptual Discovery Pipeline
          </span>
          <span className="px-2 py-0.5 rounded-[2px] bg-[#EAE7E0] text-[#56616A] text-[10px]">
            STATUS: CONCEPTUAL ARCHITECTURE
          </span>
        </div>

        {/* Pipeline Diagram Flow */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2 pt-1 text-center">
          <div className="p-3 bg-[#F4F1EA] border border-[#E4E1D9] rounded-[2px] flex flex-col justify-between h-28">
            <span className="font-mono text-[10px] text-[#7E8B96]">01. INPUT</span>
            <span className="font-semibold text-xs text-[#17202A]">Observational Stream</span>
            <span className="text-[10px] text-[#56616A]">Raw voltages / Dynamic spectra</span>
          </div>

          <div className="p-3 bg-[#F4F1EA] border border-[#E4E1D9] rounded-[2px] flex flex-col justify-between h-28">
            <span className="font-mono text-[10px] text-[#7E8B96]">02. EMBED</span>
            <span className="font-semibold text-xs text-[#17202A]">Spectrotemporal Matrix</span>
            <span className="text-[10px] text-[#56616A]">Time × Freq patches in R^512</span>
          </div>

          <div className="p-3 bg-[#F4F1EA] border border-[#E4E1D9] rounded-[2px] flex flex-col justify-between h-28">
            <span className="font-mono text-[10px] text-[#7E8B96]">03. MODEL</span>
            <span className="font-semibold text-xs text-[#17202A]">Normality Manifold</span>
            <span className="text-[10px] text-[#56616A]">Learned baseline sky topology</span>
          </div>

          <div className="p-3 bg-[#F4F1EA] border border-[#E4E1D9] rounded-[2px] flex flex-col justify-between h-28">
            <span className="font-mono text-[10px] text-[#7E8B96]">04. DETECT</span>
            <span className="font-semibold text-xs text-[#17202A]">Anomaly Estimation</span>
            <span className="text-[10px] text-[#56616A]">Residual & density outlier score</span>
          </div>

          <div className="p-3 bg-[#F4F1EA] border border-[#E4E1D9] rounded-[2px] flex flex-col justify-between h-28">
            <span className="font-mono text-[10px] text-[#7E8B96]">05. RANK</span>
            <span className="font-semibold text-xs text-[#17202A]">Candidate Scoring</span>
            <span className="text-[10px] text-[#56616A]">RFI penalties & drift coherence</span>
          </div>

          <div className="p-3 bg-[#376A9B]/10 border border-[#376A9B]/30 rounded-[2px] flex flex-col justify-between h-28">
            <span className="font-mono text-[10px] text-[#376A9B] font-semibold">06. ACTION</span>
            <span className="font-semibold text-xs text-[#17202A]">Human Review</span>
            <span className="text-[10px] text-[#376A9B]">Astrophysicist verification</span>
          </div>
        </div>

        <figcaption className="text-xs text-[#7E8B96] leading-relaxed pt-2 border-t border-[#E4E1D9]">
          <strong className="text-[#56616A]">Lifecycle Summary:</strong> Observational telemetry is
          channelized and encoded into a continuous latent space. Deviations from the learned
          baseline distribution trigger multi-parameter candidate ranking. Flagged events are
          elevated to astronomers inside the interactive AETHON workspace with complete
          spectrotemporal provenance.
        </figcaption>
      </figure>
    </section>
  );
}
